[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log
logfile_maxbytes=1048576

[program:pma-gateway-backend]
command=/opt/pma-gateway/bin/pma-gateway
autorestart=true
startsecs=2
stdout_logfile=/tmp/pma-gateway-backend.log
stdout_logfile_maxbytes=1048576
stderr_logfile=/tmp/pma-gateway-backend.err
stderr_logfile_maxbytes=1048576

[program:apache]
command=apache2-foreground
autorestart=true
startsecs=2
stdout_logfile=/tmp/apache.log
stdout_logfile_maxbytes=1048576
stderr_logfile=/tmp/apache.err
stderr_logfile_maxbytes=1048576
