[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0

[program:pma-gateway-backend]
command=/opt/pma-gateway/bin/pma-gateway
autorestart=true
startsecs=2
priority=20
stdout_logfile=/tmp/pma-gateway-backend.log
stdout_logfile_maxbytes=0
stderr_logfile=/tmp/pma-gateway-backend.err
stderr_logfile_maxbytes=0

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --fpm-config /opt/pma-gateway/php-fpm.conf
autorestart=true
startsecs=2
priority=10
stopsignal=QUIT
stdout_logfile=/tmp/php-fpm.log
stdout_logfile_maxbytes=0
stderr_logfile=/tmp/php-fpm.err
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;" -c /tmp/pma-gateway-nginx.conf
autorestart=true
startsecs=2
priority=30
stopsignal=QUIT
stdout_logfile=/tmp/nginx.log
stdout_logfile_maxbytes=0
stderr_logfile=/tmp/nginx.err
stderr_logfile_maxbytes=0
